language: swift
os: osx

matrix:
  include:
    - name: "macOS"
      script:
        - xcodebuild test -sdk macosx -project Keychain.xcodeproj -scheme Keychain_macOS
    - name: "iOS"
      script:
       - xcodebuild -sdk iphonesimulator -project Keychain.xcodeproj -scheme Keychain_iOS CODE_SIGNING_REQUIRED=NO
